minimumReleaseAgeExclude:
  - "@perishlab/bone"
  - "@perishlab/design"
  - "@perishlab/sign"
  - "@perishlab/token"

packages:
  - apps/*

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  sharp: false

catalog:
  "@biomejs/biome": 2.5.3
  "@sveltejs/vite-plugin-svelte": 7.3.1
  "@types/node": 24.13.3
  sass: 1.105.0
  svelte: 5.57.1
  svelte-check: 4.7.6
  typescript: 6.0.3
  vite: 8.3.1
  vitest: 5.0.2
