name: guard

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: guard-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  guard:
    runs-on: docker
    container:
      image: mirror.perish.lan/ci/deno
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Ectropy
        uses: PerishLab/actions/setup-ectropy@main
        with:
          channel: beta
          version: v0.4.0-beta.1

      - name: Install Plumb
        uses: PerishLab/actions/setup-plumb@main
        with:
          channel: beta
          version: v0.16.0-beta.1

      - name: Guard
        run: |
          set -eu
          deno run --allow-read "--allow-write=." --allow-env --allow-net "--allow-run=git,cargo,ectropy,plumb,deno,tea,sh,runseal,rustc,node" --config .runseal/deno.json --lock .runseal/deno.lock --frozen=true .runseal/wrappers/guard.ts --fresh
