name: release-exact

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to release
        required: true
        default: main
        type: string
      channel:
        description: Exact non-stable channel
        required: true
        default: beta
        type: string
      version:
        description: Exact non-stable version
        required: true
        type: string

permissions:
  contents: read

jobs:
  release:
    uses: PerishLab/actions/.forgejo/workflows/release-binary.yml@main
    with:
      ref: ${{ inputs.ref }}
      channel: ${{ inputs.channel }}
      version: ${{ inputs.version }}
    secrets:
      publish_access: ${{ secrets.RELEASE_PUBLISH_S3_ACCESS_KEY }}
      publish_secret: ${{ secrets.RELEASE_PUBLISH_S3_SECRET_KEY }}
      publish_bucket: ${{ secrets.RELEASE_PUBLISH_S3_BUCKET }}
      publish_endpoint: ${{ secrets.RELEASE_PUBLISH_S3_ENDPOINT }}
      registry_token: ${{ secrets.RELEASE_REGISTRY_TOKEN }}
